blank_issues_enabled: false
contact_links:
  - name: "Questions and support"
    url: "https://github.com/TypQxQ/Sigenergy-Local-Modbus/discussions"
    about: "Please use Discussions for questions or setup help."
